### PR TITLE
[Example] Express webhook

### PR DESCRIPTION
**Pull request by kamikazechaser**
A webhook integration with an express app.

References:

  * Issue #282 by @kamikazechaser

### CODE REVIEW

**Comment by kslr** [comment]
Nice, Solved my puzzle.

**Comment by kamikazechaser** [comment]
Aah the semi-colon  "requirement" :laughing:. Alright I'll pass it through a linter.

**Comment by kamikazechaser** [comment]
{Fixed] Lint

**Comment by GochoMugo** [comment]
Thanks @kamikazechaser :+1:

**Pull request merged**
