### PR TITLE
Adding callback_query

### PR DESCRIPTION
**Pull request by tionsys**
Support for responses of Inline Buttons in messages or Inline Queries

### CODE REVIEW

**Comment by highfeed** [comment]
+1

**Comment by Kaos1337** [comment]
Can you kindly provide an example as requested here https://github.com/yagop/node-telegram-bot-api/issues/109#issuecomment-221112685?

**Comment by tionsys** [comment]
Hey,
data is returned via callback_query like the Telegram Bot Api Manual states.
"msg" is an instance of CallbackQuery (https://core.telegram.org/bots/api#callbackquery)
```js
var api = new TelegramBotApi("your-token", {polling: true});

api.on('callback_query', function(msg) {
	var user = msg.from.id;
	var data = msg.data;
	api.sendMessage(msg.from.id, "You clicked button with data '"+ data +"'");
});

var options = {
	reply_markup: JSON.stringify({
	inline_keyboard: [
		[{text: 'Some button text 1', callback_data: '1'}], // Clicking will send "1"
		[{text: 'Some button text 2', callback_data: '2'}], // Clicking will send "2"
		[{text: 'Some button text 3', callback_data: '3'}]  // Clicking will send "3"
    ]
  })
};

api.sendMessage(msg.from.id, "Click a button to display data", options);
```

**Comment by Kaos1337** [comment]
Do you have any suggestion if I would:
- send a message with the inline_keyboard after the execution of a command (/mycommand)
- wait for the user interaction
- continue the execution of the code inside the command /mycommand

Why I'm asking that, well, I'd like to make a bot that uses the inline_keyboard interaction to make 2 or 3 questions to the user and at the end of all elaborate them.
An example:
- user: /calculate
- bot: choose one of these [ 1, 2, 3]
- user: <make a choise>
- bot: choose one of these [ 4, 5, 6]
- user: <make a choise>
- bot: the result is: choise1+choise2

**Comment by tionsys** [comment]
You could write a wrapper around the sendMessage funtion returning a promise or similar.
The CallbackQuery has a field called "message" where you can read the chat and message id from. 

Example:
```js
// Example wrapper
var listeners = [];
function sendButtonsMessage(text) {
	return new Promise(function(resolve, reject) {
		api.sendMessage(to, text, buttons).then(function(message) {
			listeners[listeners.length] = {chat: message.chat.id, id: message.message_id, listener: resove}
		});
	});
}

// Fetch a matching listener
api.on('callback_data', function(data) {
	for(var i = 0; i < listeners.length; i++) {
		if(listeners[i].chat != data.message.chat.id) continue;
		if(listeners[i].id != data.message.message_id) continue;
		listeners[i].listener(data);
		// Uncomment this if you want every listener to only become executed one time
		// listeners.splice(i, 1);
	}
});

// Example
sendButtonsMessage("hello").then(function userClickedAButton(button) {
	api.sendMessage(to, "You clicked on button "+ button.data);
});
```

I honestly don't recomment doing it this way, because you might have thousands of users at some time and you don't want to store that much callbacks.

**Comment by Kaos1337** [comment]
I decided to use an sql server to record every message sent that contains inline buttons with a "state", when I receive a callback_data event I check the message id and I know in which step the user is, so I can edit the inline buttons to continue the procedure and update the "state" into the db.

**Comment by paOol** [comment]
@kaos1337 can you post some pseudo code of your implementation? 

Also, couldn't you a state management library like redux instead of requiring a database

**Comment by Kaos1337** [comment]
I'm using a database because it's something that I've already adopted for that bot, so, the addition of another table wasn't a big challenge. That table records all steps where a request should go when received. (yes, it's like a final states machine)
I have a class that manages:
- the INSERT of an inline request when I've to create a new process to elaborate.
- the UPDATE of an inline request when I've change the next step.
- the DELETE of an inline request when the process finish.

The api callback_data event function has just to compare (SELECT) the message id (of the request itself) with the next step (it's all into the db) and call the relative function that allows the prosecution of the desired process. You have to keep in mind that all inline buttons could be called at any point of the time... obviously I'll deny all request older than some hours. You'll enjoy the editTextMessage call a lot.
That's all.

I'll give a look at the suggested lib.

**Comment by yagop** [comment]
`callback_query` added in #102

**Comment by rodrigosalinas** [comment]
Hi. Can you please provide a very simple example of how to use answerCallbackQuery? I don't know how to use it. Thanks in advance.

**Comment by Kaos1337** [comment]
@rodrigosalinas just call it like sendMessage: bot.answerCallbackQuery(params...);

**Pull request closed without merging**
