### PR TITLE
[API v4.0] Publish new methods and message types

### PR DESCRIPTION
**Pull request by kamikazechaser**
- [ ] All tests pass
- [x] I have run `npm run doc`

### Description
Update the library with minor changes from the latest bot API update (v4.0 released on 26/07/2018).

Add new methods:
- **editMessageMedia**
- **sendAnimation**

Add new message types:

- **passport_data**
- **animation**

### References

- #624
- [Update release notes from Telegram](https://core.telegram.org/bots/api#july-26-2018)

### CODE REVIEW

**Comment by TorlanDelta** [comment]
So how long till this gets merged? What are we waiting for?

**Comment by nathenapse** [comment]
please merge this

**Comment by kamikazechaser** [comment]
@yagop @GochoMugo If possible, merge this asap.

**Comment by yagop** [comment]
Merged. Wold be good to have tests too.

**Pull request merged**
