### PR TITLE
Fix request performance issue

### PR DESCRIPTION
**Pull request by preco21**
Fixes: https://github.com/yagop/node-telegram-bot-api/issues/77

### CODE REVIEW

**Comment by GochoMugo** [comment]
I am **not** sure you have demonstrated that performance is improved by using the [forever-agent](https://github.com/request/forever-agent).

**Comment by GochoMugo** [comment]
But we are already using the `forever` option during polling. I do **not** see why we shouldn't use the option while doing other requests against the API.
This PR seems fine to me.

/cc @yagop

**Comment by preco21** [comment]
@GochoMugo I have been using my forked version of module for my personal bot. It is working properly with better performance. I think since polling uses `forever` option already, It would be nice to have same option for requests against the APIs. 👍

**Comment by GochoMugo** [comment]
@yagop, merge this?

**Comment by GochoMugo** [comment]
PR #178 will allow one to **proxy more custom options** for the requests.

So, instead of applying the `forever` option for everyone as the default, we could instead **add note on the `forever` option in our Readme** and let users choose whether to use it or not. This helps **maintain backwards-compatibility**.

**Comment by preco21** [comment]
@GochoMugo I agree about the idea. I can write some note about this feature.

**Comment by GochoMugo** [comment]
@preco21 Nice! That would allow us to keep our API stable. Should we decide to break it, we might add this option.

**Comment by preco21** [comment]
@GochoMugo Since polling uses `forever` option already, you can consider about adding option that directly adding `forever` option to requst functions without through proxy object for taking balance of the API.

**Comment by GochoMugo** [comment]
Thanks @preco21 for your time and effort!

**Comment by preco21** [comment]
@GochoMugo Awesome! ✨

**Pull request merged**
