### PR TITLE
fixed #207 

### LINKED ISSUE #207: request-promise causes memory leaks
The current version of request-promise looks like contain a memory leak (related to #52) because of internal cache implementation according to Chrome profile. I've updated `package.json` with request-promise ^4.1.1 and it looks the problem with leaks was mitigated. 

You can reproduce the problem by increasing timer interval to 10 and leave it for an hour.

### PR DESCRIPTION
**Pull request by desunit**
updated request-promise package to eliminate memory leaks

### CODE REVIEW

**Comment by GochoMugo** [comment]
Just for formality, have you ensured we have satisfied all the migration guidelines, [as stated in the `request-promise` documentation](https://github.com/request/request-promise#readme)?

**Comment by desunit** [comment]
The major changes related to transform which is not used in this code. We upgraded the code for our production and it works for more than week without memory leaks and issues.

**Comment by CapacitorSet** [comment]
Very nice. I have been using this "in production" and the server no longer crashes.

**Comment by desunit** [comment]
@CapacitorSet, glad to hear that!

**Comment by GochoMugo** [comment]
My summary:

* [x] ~~... make sure that request is installed into your project as a direct dependency ...~~ we already installing request as a direct dependency!
* [x] ~~... Continuation Local Storage is no longer supported ...~~ we do **not** use Local Storage!
* [x] ~~... your transform function ...~~ we do **not** use Transform function!
* [x] ~~... handling of the transform function got overhauled ...~~ we do **not** use Transform function!
* [x] ~~... Bluebird got updated from v2 to v3 ...~~ we already using v3

We are ok to merge this! Will be in next release!

Thanks @desunit for your time and effort!

**Comment by GochoMugo** [comment]
This closes issues #202 and #207.

**Comment by desunit** [comment]
Thanks @GochoMugo! I think it should close #52 too.

**Comment by GochoMugo** [comment]
We might need to confirm with the original thread creator and contributors.

**Pull request merged**
