### PR TITLE
Add sendDocument method

### PR DESCRIPTION
**Pull request by Waterloo**

### CODE REVIEW

**Comment by Waterloo** [comment]
Test failed because the Bot token is not provided

**Comment by yagop** [comment]
It's a Travis feature, private environment variables aren't evaluted on PR.

**Comment by yagop** [comment]
`Unhandled rejection Error: 400 {"ok":false,"error_code":400,"description":"Error: Bad Request: Type of file to send mismatch"}`

**Comment by Waterloo** [comment]
but i am able to send gif images as documents :disappointed:

**Comment by yagop** [comment]
Fixed on 3ed643f

**Comment by Hunter-Github** [comment]
@yagop - any plans on npm-publishing the next release? "Release early, release often" :)

**Pull request merged**
