### PR TITLE
Fixed issue where inline keyboards wouldn't appear when sending somet…

### PR DESCRIPTION
**Pull request by tengotengo**
there, should work now

### CODE REVIEW

**Comment by seeya** [comment]
thanks, it worked for me

**Comment by koloboid** [comment]
@yagop let's merge?

**Comment by GochoMugo** [comment]
**Duplicate of #133**

**Comment by GochoMugo** [comment]
This bug has been fixed in PR #133.

Thank you @tengotengo for your time and effort! :+1:

**Pull request closed without merging**
