### PR TITLE
Add `stopPolling` method

### PR DESCRIPTION
**Pull request by smmoosavi**
usage:
```js
var bot = new TelegramBot(token, {});

bot.initPolling(); // polling started

bot.initPolling(); // polling restart

bot.stopPolling(); // new method: polling stoped
```

### CODE REVIEW

**Comment by phillipadsmith** [comment]
@yagop Any timeline on merging in one of the two PRs to implement a stopPolling method?

**Comment by yagop** [comment]
This can be achieved by:
```
this._polling.abort = true;
this._polling.lastRequest.cancel('Stop polling');
```
Which is what the `stopPolling` does.

**Comment by phillipadsmith** [comment]
> This can be achieved by:

Yes, I realize that, and yet I'm wondering why there is not stopPolling() method in node-telegram-bot-api when there are two PRs in the queue that propose implementing it? Is there a reason not to have a stopPolling() method?

**Comment by icdevin** [comment]
I kind of agree, and really the `._polling` typically denotes an internal property, which you want to avoid calling or settings.

**Comment by smmoosavi** [comment]
until this and other poll request merged, you can use this [monkey patch](https://github.com/monkey-patches/node-telegram-bot-api)

**Comment by phillipadsmith** [comment]
@yagop Bump.

**Comment by GochoMugo** [comment]
This has already been implemented in our codebase. Thanks for your time and effort.

**Pull request closed without merging**
