### PR TITLE
Add filename parsing

### PR DESCRIPTION
**Pull request by rkhitin**
Parsing filename from remote files stream let show right name in message. For example 'cat.gif' instead 'undefined', and telegram show preview for img in case if we read stream by url.

### CODE REVIEW

**Comment by yagop** [comment]
It shouldn't be implemented on `_request` funciton but in `formatSendData`

**Comment by rkhitin** [comment]
Now it's in `formatSendData` and little bit cleaner.

**Comment by GochoMugo** [comment]
Is it possible to add an example, where this is necessary?

**Comment by GochoMugo** [comment]
This PR will be closed after some time! Please provide more information!

**Comment by GochoMugo** [comment]
Closing this Cold PR! It got stale!

**Pull request closed without merging**
