### PR TITLE
Initial support for games

### PR DESCRIPTION
**Pull request by jishnu7**

### CODE REVIEW

**Comment by jishnu7** [comment]
thanks @GochoMugo . Updated with generate Readme

**Comment by jishnu7** [comment]
@GochoMugo There is no change in README.hbs. These functions are part of the class which already exist in hbs file.

**Comment by GochoMugo** [comment]
ooh, my bad! Yeah, seems correct now.

FYI: squashing the commits into one is always a :+1: for a PR

Otherwise, nice job! Thanks!

**Comment by seufry** [comment]
I tried it, but I do not get the inline_query or chosen_inline_result events when I push button 'Play GAME_NAME'. This is my mistake?

**Comment by seufry** [comment]
I put console.log in `message`, `inline_query` and `chosen_inline_result` events handlers, and when I press the play button, they do not work.

**Comment by GochoMugo** [comment]
@jishnu7: Could you implement the [getGameHighScores](https://core.telegram.org/bots/api#getgamehighscores) method?

@seufry: Use the `"callback_query"` event. It is **not** currently documented (see PR #163 for more info on it). See Bot API documentation mentioning [callbackQuery](https://core.telegram.org/bots/api#callbackquery) at [Games](https://core.telegram.org/bots/api#games).

**Comment by seufry** [comment]
@GochoMugo thanks, it works!

**Comment by GochoMugo** [comment]
Thanks @jishnu7 for your time and effort in this PR! :+1:

**Comment by jishnu7** [comment]
@GochoMugo Will implement and send getGameHighscrore in a new PR.

**Comment by GochoMugo** [comment]
@jishnu7 Yeap! Waiting for your PR.

**Pull request merged**
