### PR TITLE
Add getStickerSet

### PR DESCRIPTION
**Pull request by CapacitorSet**
- [ ] All tests pass
- [x] I have run `npm run gen-doc`

### Description

Implements `getStickerSet` (part of the Bot API 3.2: #407).

### References

The original PR was #389. Seeing that it was abandoned, I fixed it.

### CODE REVIEW

**Comment by CapacitorSet** [comment]
Huh?

**Comment by GochoMugo** [comment]
Hold on. Just messed up things. :smile:

**Comment by GochoMugo** [comment]
Crap! Just restore your `master` branch. Seems this situation can not be salvaged.

**Comment by CapacitorSet** [comment]
Uh, what happened? Was it me that messed up something in the PR? I can't quite figure out what happened.

**Comment by CapacitorSet** [comment]
Oh wait, I see now. I'll restore master right away.

**Comment by CapacitorSet** [comment]
Done!

**Comment by GochoMugo** [comment]
Merged in commit https://github.com/yagop/node-telegram-bot-api/commit/a2d85b889ad2f58879590b9f65f1fc130c2575bc.

Thanks @CapacitorSet and @LibertyLocked for the PR! Thanks! :+1:

**Pull request closed without merging**
