### PR TITLE
add callback_query processing

### PR DESCRIPTION
**Pull request by vtsyganov**

### CODE REVIEW

**Comment by icdevin** [comment]
This will be added with #102 when my PR to @tjhorner accepts mine and then @yagop accepts the combined PR.

**Comment by tjhorner** [comment]
tjhorner/node-telegram-bot-api#2 accepted :)

**Comment by yagop** [comment]
Tets retutns a Promise so no need for `done` call.

https://mochajs.org/#working-with-promises

**Comment by edlvj** [comment]
@yagop Please create or accept callback_query processing.
 Because other forks of this project don't generating /src and have problems with babel .

**Comment by zigzag-way** [comment]
Looks like I have to change this library for smth else... (((

**Comment by yagop** [comment]
Thanks!
Done in #102

**Pull request closed without merging**
