### PR TITLE
Added mention of `callback_query` in README.md

### PR DESCRIPTION
**Pull request by Cameri**

### CODE REVIEW

**Comment by GochoMugo** [comment]
I think you should not make changes to the README.md. It is 'compiled' from README.hbs, using `npm run gen-doc`!

**Comment by Cameri** [comment]
Disregard my PR then. I will update the other file.

**Comment by GochoMugo** [comment]
Also, I notice there is another PR, #163, that addresses your change. You might want to coordinate there.

**Comment by GochoMugo** [comment]
This has been handled in PR #163.

Thank you @Cameri for your time and effort in this PR! :+1:

**Pull request closed without merging**
