### PR TITLE
Added `waitResponse` utility method

### PR DESCRIPTION
**Pull request by rlogiacco**
I believe this method will be very appreciated as it greatly simplifies user interaction into bots!

### CODE REVIEW

**Comment by yagop** [comment]
Really interesting I like it too much!. I was working with another solution which don't uses promises (but a callback that can be executed many times).

**Comment by yagop** [comment]
Closed by 17cb062c9642313f17c3c5e070de2032031857d3

**Comment by rlogiacco** [comment]
I see your implementation is quite different.... I personally prefer promises over callbacks... Do you mind if I publish an alternative npm module?

**Comment by yagop** [comment]
I prefer promises over callbacks too but a Promise can't be called (resolved) more than once. There can be multiple replies to the same message.

**Comment by yagop** [comment]
Of course, you can alternative npm module, this is OpenSource :blue_heart:

**Comment by rlogiacco** [comment]
> There can be multiple replies to the same message.
I believe we are taking two different approaches, but I understand your point.

I've just added another feature, an `onCommand` function which splits arguments by commas: a little less flexible than `onText` but simpler for the end user in the most common cases, I believe.

Have a look at my fork if you wish, I will not submit a pull request

:+1:

**Pull request closed without merging**
