### PR TITLE
Added setMessageReaction

### PR DESCRIPTION
**Pull request by fede1132**
- [x] All tests pass
- [x] I have run `npm run doc`

### Description

Added implementation of setMessageReaction telegram api

### References

Issue: https://github.com/yagop/node-telegram-bot-api/issues/1012

### CODE REVIEW

**Review by kamikazechaser — APPROVED** [review]
LGTM

**Comment by RichardPickman** [comment]
> We have this method already from other more old pull request. Thank you also for your contribution ✋
> 
> Note: It is not necessary to use "JSON.stringify", in the library we use the "stringify" helper function

Is there any info how it is called now? Can't find any

**Comment by danielperez9430** [comment]
> > We have this method already from other more old pull request. Thank you also for your contribution ✋
> > Note: It is not necessary to use "JSON.stringify", in the library we use the "stringify" helper function
> 
> Is there any info how it is called now? Can't find any

Is the method `setMessageReaction` 

Include since the 0.65 version: 

https://github.com/yagop/node-telegram-bot-api/blob/master/CHANGELOG.md#06500650---2024-02-20

**Comment by RichardPickman** [comment]
> > > We have this method already from other more old pull request. Thank you also for your contribution ✋
> > > Note: It is not necessary to use "JSON.stringify", in the library we use the "stringify" helper function
> > 
> > 
> > Is there any info how it is called now? Can't find any
> 
> Is the method `setMessageReaction`
> 
> Include since the 0.65 version:
> 
> https://github.com/yagop/node-telegram-bot-api/blob/master/CHANGELOG.md#06500650---2024-02-20
> 
> Use example:
> 
> bot.setMessageReaction(chatId, messageId, options)
> 
> Note: options will be an object with the optional params that you can see in the telegram bot api docs.
> image Reference: https://core.telegram.org/bots/api#setmessagereaction

OOOOOH, I GET IT NOW. The version of types package is ^0.64.7, that is the reason why I don't get any suggestions with types. But the package itself is version 0.66

**Pull request closed without merging**
