### PR TITLE
Fixed show_alert being required in answerCallbackQuery()

### PR DESCRIPTION
**Pull request by mnb3000**
- [x] All tests pass
- [x] I have run `npm run gen-doc`

### Description

Made `show_alert` optional in `answerCallbackQuery()` method

### References

* Issue #367: https://github.com/yagop/node-telegram-bot-api/issues/367
* Telegram Bot API - answerCallbackQuery: https://core.telegram.org/bots/api#answercallbackquery

### CODE REVIEW

**Comment by mnb3000** [comment]
@GochoMugo @yagop Maybe i should make it support both variants (specifying show_alert in method's params and in options object)?

**Comment by GochoMugo** [comment]
Yes, it should support both variants to ensure backwards compatibility. See https://github.com/yagop/node-telegram-bot-api/blob/61e8f8536818a2d98c81cbb92c764ec0d58ed989/src/telegram.js#L456-L468 for an example on how we do/did it.

**Comment by mnb3000** [comment]
@GochoMugo Done

**Comment by mnb3000** [comment]
`[older, compatible signature][answerCallbackQuery-v0.27.1]` syntax doesn't make a link to older docs from release src, what am I doing wrong

**Comment by GochoMugo** [comment]
You have to append the appropriate URL to `doc/api.hbs` (i.e. at the bottom of the file).

**Comment by mnb3000** [comment]
Done. Repo is not updated to 3.1 update, resolve the conflict manually while merging

**Comment by GochoMugo** [comment]
Merged in commit [4ed6d945ab4596a92aff294a47e3440576c835fa](https://github.com/yagop/node-telegram-bot-api/commit/4ed6d945ab4596a92aff294a47e3440576c835fa).

Thanks @mnb3000 for contributing to this library. :+1: 

<p align="right">#MERGE</p>

**Pull request closed without merging**
