### PR TITLE
chore: Replace request to node-fetch, #1076

### PR DESCRIPTION
**Pull request by Dima-Dim**
- [x] All tests pass
- [x] I have run `npm run doc`

About tests:
I don't have TEST_STICKER_SET_NAME and TEST_PROVIDER_TOKEN to run the tests related to them. The rest of the test pass normally.

### Description
Getting rid of deprecated dependencies request.

### References
https://www.npmjs.com/package/request

Issue: #1076.

### CODE REVIEW

**Comment by kamikazechaser** [comment]
Looks like a good change if all tests pass, though Node.js has a built in fetch API in newer version (18+).

**Comment by Dima-Dim** [comment]
> Looks like a good change if all tests pass, though Node.js has a built in fetch API in newer version (18+).

Yes, after some time it will be possible to try to completely switch to a native solution, but i think no before end of support version older than 18.

**Comment by 0x114514BB** [comment]
Your change literally removed the `request` dependency. The core `_request` function of NTBA depends on `request-promise` (also deprecated), which has `request` [as a peer-dependency](https://www.npmjs.com/package/request-promise-core). So you should replace it with `node-fetch` or other solutions.

**Comment by danielperez9430** [comment]
For the moment we have already a remplace for the request library merge and without need to drop support for the current old versions.

In a future completed refactor, we will be drop the support for older versions of node. But for the moment we still preserve the compatibility.

**Pull request closed without merging**
