### PR TITLE
Added support for "deleteMessage" method

### PR DESCRIPTION
**Pull request by JonasFowl**
- [ ] All tests pass
- [ ] I have run `npm run gen-doc`

### Description

Added the ability to delete messages with a bot.

### References
* Telegram Bot API - Deleting messages:  https://core.telegram.org/bots/api#deleteMessage

### CODE REVIEW

**Comment by GochoMugo** [comment]
I do **not** seem to find such a method stated in the documentation.

**Comment by krizka** [comment]
Me too. Is it secret one?

**Comment by dotcypress** [comment]
@krizka @GochoMugo @JonasFowl this method isn't released yet.

**Comment by GochoMugo** [comment]
I am open to merging this in but with the condition that it goes into a new branch, named `experimental`. We shall merge into `master` once an official update has been made to the Bot API. Developers would have to use `github:yagop/node-telegram-bot-api#experimental` in their `package.json` (or to `npm install`) to install these experimental features. What do you think?

/cc @yagop

**Comment by yagop** [comment]
Did the reference vanished?

Perfect with creating new `experimental` branch.

**Comment by yagop** [comment]
A test case will be also welcome when API method released.

**Comment by GochoMugo** [comment]
@JonasFowl Please add  tests for this method.

@yagop Creating experimental branch...

**Comment by JonasFowl** [comment]
@GochoMugo I would like to do so, but unfortunatly I am to stupid to do so.

**Comment by GochoMugo** [comment]
Merged into `experimental` branch in commit https://github.com/yagop/node-telegram-bot-api/commit/bab2ec66d83118ed969251a97f933b66ae811e3b.

Thanks @JonasFowl for the PR! :+1: 

*PS: PR will be closed once docs are updated with instructions on how to use experimental features.*

**Comment by GochoMugo** [comment]
Closing this PR now. Docs have been updated.

Any follow up at issue #323.

**Pull request closed without merging**
