### PR TITLE
Added basic support for the new inline API

### PR DESCRIPTION
**Pull request by crisbal**
For listening to the new events and for sending inline replies.

### CODE REVIEW

**Comment by yagop** [comment]
Thaks :+1: your PR is very appreciated. 
I read your Telegram messages but I [couldn’t answer](https://cloud.githubusercontent.com/assets/5002453/12099090/8eb2d578-b326-11e5-9eb7-30fdb4163f73.jpg) you because I got banned, sorry.
I will test a bit and merge it

**Comment by crisbal** [comment]
Ok, no problem. I tested it a bit on my bot project and seems to be working. 

If you want to speak with me on telegram I can send you my contact and you can talk with me even with the ban.

**Comment by crisbal** [comment]
Ok, I tested it with a few friends for half an hour using this code 

```TelegramBot = require('./src/telegram');


var bot = new TelegramBot(TOKEN, {
    polling: true
});

bot.on("inline_query", function(inline_query){
    bot.answerInlineQuery(inline_query.id, [{id: '0', type:'article', title:"Click here now.", description: "You will get markdown output", message_text: inline_query.query, parse_mode: 'Markdown'}]);
});```

Which basically allow the user to get markdown rendered on a text he sent.

**Comment by yagop** [comment]
Seem its enough if you send me 10 messages

**Comment by yagop** [comment]
I wasn't able to receive an `chosen_inline_result` did you?

**Comment by crisbal** [comment]
Me neither. I don't know why the API has the specification for it but it does not work.

**Pull request merged**
