### PR TITLE
allow 0ms for polling interval

### LINKED ISSUE #20: Use 0ms as polling interval value
Hi!

I would like to perform long polling like this:

```js
var bot = new TelegramBot(token, { polling: { timeout: 2000, interval: 0 } });
```

The problem is that 0 is replaced with default 2000ms inside the module. I can use `interval: 1`. It solves the issue but doesn't feel right. Is there any other way to perform long polling?

### PR DESCRIPTION
**Pull request by brandly**
fixes #20. thanks!!

by the way, i'm seeing a lot of tests fail locally due to `PEER_ID_INVALID`. it looks like i should probably set a `TEST_USER_ID`, but i'm not sure where to get that value from. thanks again

### CODE REVIEW

**Comment by yagop** [comment]
I don't know why people want to do 0ms pooling interval, its really annoying for server and client, its just like DDoSing Telegram.

`TEST_USER_ID` is a user id (or chat) to send the messages. A bot can only send messages to a user if he has sent a message before.

**Comment by brandly** [comment]
hahahah that's fair. i just saw the issue and figured i could fix it easily.

how's the CI server supposed to work, if keys aren't hardcoded? AppVeyor is throwing `'Bot token not provided'`

**Comment by yagop** [comment]
For security Travis and AppVeyor don't expose environment variables on pull requests. I set up Travis to not building on PR, AppVeyor now doesn't build too.

**Comment by brandly** [comment]
thanks for the explanation!

if there's no need for 0ms polling, you're more than welcome to close this PR. in that case, i'd close #20 as well

**Comment by yagop** [comment]
You are welcome.
Done, thanks.

**Pull request merged**
