### PR TITLE
src/telegram: Allow specifying mime type when sending files

### PR DESCRIPTION
**Pull request by GochoMugo**
- [ ] All tests pass
- [x] I have run `npm run gen-doc`

### References

 * FR: https://github.com/yagop/node-telegram-bot-api/issues/350

### CODE REVIEW

**Comment by Hypfer** [comment]
image

image


Well.

**Comment by GochoMugo** [comment]
@Hypfer I have corrected the check-box state (for accuracy).

*PS: Some tests were already broken! :disappointed:*

**Comment by GochoMugo** [comment]
Overridden by PR #471.

**Pull request closed without merging**
