### PR TITLE
Telegram Bot API 5.0 Support

### PR DESCRIPTION
**Pull request by danielperez9430**
### Description
Added full support for new bot api methods. 

New methods:
- copyMessage()
- unpinAllChatMessages()
- close()
- logOut()

Add Tests for this methods:
- copyMessage()
- unpinAllChatMessages()

### References

[https://core.telegram.org/bots/api-changelog#November-4-2020](https://core.telegram.org/bots/api-changelog#November-4-2020)

### CODE REVIEW

**Comment by danielperez9430** [comment]
All passed tests:

imagen

**Comment by codemighty** [comment]
@yagop , could you merge this pull request ASAP?

**Comment by XieJiSS** [comment]
> @yagop , could you merge this pull request ASAP?

I think you'd better create a fork and publish it to npm under an organization prefix (i.e. `@xxx/node-telegram-bot-api`), as a temporary workaround.

According to previous records, it may take weeks for yagop to see & merge this

**Comment by XieJiSS** [comment]
@danielperez9430 and I think the version should be bumped to 0.51? Cause this update contains several new APIs.

By doing so, we can easily update `@types/node-telegram-bot-api` later.

**Comment by danielperez9430** [comment]
> @danielperez9430 and I think the version should be bumped to 0.51? Cause this update contains several new APIs.
> 
> By doing so, we can easily update `@types/node-telegram-bot-api` later.

Okey, I update the version to 0.51.0

**Comment by codemighty** [comment]
@XieJiSS 
> I think you'd better create a fork and publish it to npm under an organization prefix (i.e. `@xxx/node-telegram-bot-api`), as a temporary workaround.
Thanks for the advice. I've already created a temp workaround for my local experiments absolutely as you described, but for further work with this library in prod environment it'll be great to upgrade it up to API 5.0 support.

**Comment by danielperez9430** [comment]
> @XieJiSS 
> > I think you'd better create a fork and publish it to npm under an organization prefix (i.e. `@xxx/node-telegram-bot-api`), as a temporary workaround.
> 
> Thanks for the advice. I've already created a temp workaround for my local experiments absolutely as you described, but for further work with this library in prod environment it'll be great to upgrade it up to API 5.0 support.

Don't worry that the changes will be applied soon, I have news from one of their maintainers and we will have the update shortly.

**Comment by kamikazechaser** [comment]
Thanks @danielperez9430 !

**Pull request merged**
