### PR TITLE
Add new method sendDice, getMyCommands, setMyCommands and more

### PR DESCRIPTION
**Pull request by danielperez9430**
- [X] Documentation updated
- [X] Local test

### Description
Update the library with minor changes from the latest bot API update (v4.7 released on 30/03/2020) and bot API v4.8  24/04/2020

Add new methods:
- sendDice
- getMyCommands
- setMyCommands
- setChatAdministratorCustomTitle
- setChatPermissions

Add new message type:
- dice

Add test:
- sendDice
- getMyCommands
- setMyCommands
- setChatAdministratorCustomTitle
- setChatPermissions

Fixed old test:
- New photo for sendPhoto (no gif)
- New photo for setChatPhoto (older bug with Telegram API - Tg Server Bug)

Add support for poll_answer (by @JieJiSS from https://github.com/yagop/node-telegram-bot-api/pull/777)

## References
[Telegram Bot API update note v4.7](https://core.telegram.org/bots/api#march-30-2020)
[Telegram Bot API update note v4.8](https://core.telegram.org/bots/api#april-24-2020)
[Telegram Bot API update note v4.5](https://core.telegram.org/bots/api#december-31-2019)

### CODE REVIEW

**Comment by kamikazechaser** [comment]
Thanks for the PR. Could you add some tests for the method?

**Comment by danielperez9430** [comment]
> Thanks for the PR. Could you add some tests for the method?

Could you see the message thta I sent you on Telegram?

**Comment by danielperez9430** [comment]
# sendDice Examples

**Comment by kamikazechaser** [comment]
Changes are fine. I will try to merge this asap. If you get time, you could add tests.

**Comment by danielperez9430** [comment]
## NEW

Example setChatAdministratorCustomTitle:
```js
bot.promoteChatMember(chat_id, user_id, {can_invite_users: true}).then(msg => {
	console.log(msg);
bot.setChatAdministratorCustomTitle(chat_id, user_id, "hello");
}
);
```

Example setChatPermissions:

```js
const ChatPermissions = {
	can_send_messages: false
};
bot.setChatPermissions(chat_id, ChatPermissions);
```

**Comment by danielperez9430** [comment]
@kamikazechaser you need to FIX Travis, missing Bot Token

**Comment by kamikazechaser** [comment]
> @kamikazechaser you need to FIX Travis, missing Bot Token 

Travis doesn't allow secrets in PRs now. Also I don't have full access to this repo or npm. So I cannot change how the CI works.

**Comment by danielperez9430** [comment]
@kamikazechaser In principle the tests now work, between today and tomorrow I add the missing tests.

I'll talk to Yago about Travis, thanks you

**Comment by danielperez9430** [comment]
And all Test Pass 🥇

**Comment by danielperez9430** [comment]
@kamikazechaser I made a cherry pick of @JieJiSS changes and added his contribution in the changelog.

Only the tests of the sendPoll method are missing. I will try to have them finished today

**Comment by danielperez9430** [comment]
## sendPoll - Examples

Get the first answer each user makes
```js
bot.on('poll', (msg) => {
	console.log(msg);
} );
```
Obtain the modifications that a user makes in the poll such as withdrawing the vote or changing it
```js
bot.on('poll_answer', (msg) => {
	console.log(msg);
} );
```

**Comment by danielperez9430** [comment]
## And Work 🦺

**Pull request merged**
