### PR TITLE
Middleware

### PR DESCRIPTION
**Pull request by GuidoNebiolo**
- [ ] All tests pass
- [x] I have run `npm run gen-doc`

### Description

TelegramBot object now expose the method use to insert a middleware to manage the incoming message.

### References

Issue #242

### CODE REVIEW

**Comment by GochoMugo** [comment]
Is it possible to come up with an example illustrating a simple use case where this new feature is being used? It would really help in designing and validating the feature.

Otherwise, we are happy to see a PR! :100:

**Comment by GuidoNebiolo** [comment]
Sure! for example it's possible to creating a simple authentication middleware like this one:
`
bot.use((message, next) => {
  const chatId = message.chat.id;
  if (chatId === 1234) {
    next();
  } else {
    bot.sendMessage(chatId, 'Chat unauthorized');
  }
});
`
or a middle for analytics like the issue #242 

It's possible to build a chain of many middleware and break the chain avoiding the next method calling.

**Comment by GochoMugo** [comment]
Why are text messages (and **not** other types of messages) used in handling the middlewares? Is it possible to allow all types of messages?

**Comment by GuidoNebiolo** [comment]
I can change the code and pass the update object (the same of the method processUpdate (https://core.telegram.org/bots/api#update) instead of message object inside the middleware.
Do you thing this could be useful?

**Comment by GuidoNebiolo** [comment]
Now the middleware function accept as first argument the update object.
This is an example of how to use it:
```javascript
bot.use((update, next) => {
  console.log(update);
  next();
}).use((update, next) => {
  if (!!update.message) {
    const chatId = update.message.chat.id;
    if (chatId === 1234) {
      next();
    } else {
      bot.sendMessage(chatId, 'Chat unauthorized');
    }
  }
});
```
You can also chain more use method.

**Comment by GochoMugo** [comment]
Things are looking better. Here are some suggestions:

1. It would be better if the `processUpdate()` method remain largely same as before. Just before emitting the relevant events, we would handle the middlewares (using a `_executeMiddlewares()` method, for example). 

2. How do the middlewares and the rest of update processing work together? Are events *always* emitted even if a middleware stops the chain execution i.e. events and middlewares are independent of each other. Or would it work like below, where the middlewares affect the events:

```js
processUpdate(...) {
    ...
    // the callback is invoked if all the middlewares invoke `next()` in their executions!
    return this._executeMiddlewares(update, function() {
        // the events are now emitted, etc.
        // ...
    });
}
```

What do you think?

**Comment by MCSH** [comment]
IMO the events should be emitted only if all of the middlewares have called next. 

Also, would it be possible to change the event inside a middleware? An example would be that I have a "nickname" field in database for each userid and I'd like the 'chat' or 'from' part of each message to have that nickname as well, will I be able to do this?

**Comment by GochoMugo** [comment]
Yeah, that should be possible, just like in Express. The middlewares can mutate the Update object.

**Comment by noamcore** [comment]
This pull request was abandoned?

**Comment by muety** [comment]
Would love to have support for middlewares!

**Pull request closed without merging**
